### ISSUE TITLE
"MYSCHEMA.sessions" is an undefined name

### ISSUE THREAD

**Issue by Mouad-B** [wallali/connect-db2#4]
When I try to connect to SESSIONS table which I created in the appropriate schema, I get this error [IBM][CLI Driver][DB2/LINUXX8664] SQL0204N "MYSCHEMA.sessions" is an undefined name.  SQLSTATE=42704  
I pass the dsn to the session like this:
```
var session = require("express-session")
  , Db2Store = require('connect-db2')(session);
var options = {
  dsn: 'DATABASE=MyDB;HOSTNAME=IpAddr;PORT=myPort;PROTOCOL=TCPIP;UID=db2_admin;PWD=db2_pwd;CurrentSchema=MYSCHEMA;'
}
var sessionStore = new Db2Store(options);
app.use(session({
  store: sessionStore,
  secret: "AAAAA:ZZZZZ:EEEEE"
}));
```
Did I miss something here ?

**Comment by wallali** [comment]
Hi,

Table names can be case sensitive. Can you share your schema. Is your table all lowercase "sessions".

**Comment by Mouad-B** [comment]
I corrected the table name and now gets this message error:

> Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  "session_id" is not valid in the context where it is used.  SQLSTATE=42703 
> 
>    at Error (native)

Here how I generated the sessions table:
```
CREATE TABLE "MYSCHEMA.sessions" ("session_id" VARCHAR(255) NOT NULL PRIMARY KEY, "expires" BIGINT NOT NULL, "data" VARCHAR(8100))  organize by row

CREATE INDEX "MYSCHEMA.sessions|expires" ON "MYSCHEMA.sessions" ("expires")
```

**Comment by wallali** [comment]
You will have to provide more information than that to isolate the issue. If you set in your environment `DEBUG=connect:db2` it should print out additional messages in the console to help you where it is going wrong.

**Comment by Mouad-B** [comment]
Here what I get on debug mode:

>   connect:db2 Getting session "oONAym1e-49TAFmtxflSxeQRN8d0V0ls" +0ms
>   connect:db2 Failed to get session +133ms
>   connect:db2 Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  "session_id" is not v
> alid in the context where it is used.  SQLSTATE=42703
> 
>     at Error (native) +2ms
> GET / 500 144.816 ms - 186
> Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  "session_id" is not valid in the co
> ntext where it is used.  SQLSTATE=42703
>

**Comment by wallali** [comment]
okay so on line 195: https://github.com/wallali/connect-db2/blob/master/lib/connect-db2.js#L195

if you add a `console.log(sql)` it should tell you the SQL it is running. See if that is valid.

Column names are also case sensitive

**Comment by Mouad-B** [comment]
The query is:
`SELECT "data" AS "data" FROM "sessions" WHERE "session_id" = ? AND "expires" >= ?`
It seems that the double quotes around session_id, expires and data are causing the issue. When removing them, everything works fine

**Comment by wallali** [comment]
hmm, are you using db2 on Bluemix? From what I have seen without the quotes Dash DB looks for the SESSION_ID column instead of the session_id column (auto capitalises).

See:
https://www.ibm.com/developerworks/data/library/techarticle/0203adamache/0203adamache.html#N1011C

**Comment by Mouad-B** [comment]
I'm not using db2 on bluemix. I know about the auto capitalises issue, that's why I kept the quotes around the table name and the As clause but it seems that when putting them around the column names it looks for "session_id" instead of session_id for exemple.

**Comment by Mouad-B** [comment]
I can make a pull request with the modification if you wish. The module works perfectly fine now !

**Comment by wallali** [comment]
Hi, I see you have closed this. Did you find another solution?

If not, here is my take on this issue:
Because DB2 on Bluemix requires quotes for lower case table and column names, the best solution would be to remove quotes from table and column names and let the DBs default behaviour kick in. This would however be a breaking change to this module. Something I need to do over a weekend.

**Comment by Mouad-B** [comment]
Hello, I found that my columns were with capital letters that's why I had to change the module to match.
I corrected my my table and everything works fine with the original version.
Thank you for your help !
